# https://alacritty.org/config-alacritty.html

[font]
size = 13

[font.normal]
family = "InputMono Nerd Font"

[window]
startup_mode = "Windowed"
opacity = 0.95
decorations = "Buttonless"
padding = { x = 8, y = 8}

[env]
TERM = "xterm-256color"
